name: Docker CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for multi-platform support (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image and tag it
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mkasraoui_backend:latest .

      # Step 5: Push the image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mkasraoui_backend:latest
  deploy_to_vps:
    runs-on: ubuntu-latest
    needs: build_and_push_image  # Ensures this job runs only after the image is pushed
    steps:
      # Step 1: SSH into VPS and deploy the updated Docker image
      - name: SSH into VPS and deploy the updated Docker image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Stop the currently running container
            docker compose down

            # Pull the latest image from Docker Hub
            docker compose -f compose.yml pull

            # Start the container with the latest image
            docker compose up -d

            # Clean up unused Docker images to free up space
            docker image prune -f

            # Remove unused Docker volumes to free up space
            docker volume prune -f
